@startuml "Activity diagram"
title "Game flow"

start
:Start game;
repeat :System start timer of the player;
:Player choose a chess piece to move;
:System show valid moves;
:Player choose a destination cell;
:System move the chess piece;
:System pause timer of the player;
:System check is game over;
:Switch player;
repeat while (game not over)
:End game;
stop

@enduml
