@startuml "Chess game"
hide circle

class Board {
  - cells: Cell[][]
  + moveChessPiece(chessPiece: ChessPieceBase, destinationCell: Cell)
  - checkEndGame()
  - setUpBoard(chessPieces: ChessPieceBase[])
}

class Cell {
  - row: number
  - column: number
  - chessPiece: ChessPieceBase
  + setChessPiece(chessPiece: ChessPieceBase)
  + getChessPiece(): ChessPieceBase
}

class Player {
  - moveChessPiece(chessPiece: ChessPieceBase, destinationCell: Cell)
  - undoMove()
  - redoMove()
}

class ChessPieceBase {
  - moveStrategies: IMoveStrategy[]
  + setPlayer(player: Player)
  + checkAvailableMoveCells()
  + doMove()
}

interface IMoveStrategy { 
  + checkAvailableMoveCells()
  + doMove()
}

class MoveStraight implements IMoveStrategy { }

class MoveDiagonal implements IMoveStrategy { }

class MoveL implements IMoveStrategy { }

class MaxRangeDecorator implements IMoveStrategy {
  - IMoveStrategy move
}

class OnlyFowardDecorator implements IMoveStrategy {
  - IMoveStrategy move
}

class Game {
  - board: Board
  - history: History
  - whitePlayer: Player
  - blackPlayer: Player
  + startGame()
  + endGame()
  + undoMove()
  + redoMove()
  + showHistory()
}

class History { 
  - moves: HistoryMove[]
  - redoMoves: HistoryMove[]
  + getMove(index: number): HistoryMove
  + addMove(chessPiece: ChessPieceBase, destinationCell: Cell)
  + showHistory()
  + undoMove()
  + redoMove()
}

class HistoryMove {
  - chessPiece: ChessPieceBase
  - destinationCell: Cell
}

ChessPieceBase -down-o IMoveStrategy

Board -down-o Cell
Board -down-o ChessPieceBase
Board .right.> History

History -down-* HistoryMove

Game -down-o Board
Game -down-o History
Game -down-o Player

Player .up.> Board
Player .up.> Game

@enduml