@startuml "Use case"
left to right direction

actor Player


rectangle Match {
  
  usecase "Undo move" as undoMove
  usecase "Redo move" as redoMove
  usecase "View move history" as viewMoveHistory
  usecase "Surrender" as surrender
  usecase "Save game" as saveGame
  usecase "Move a chess piece" as moveAChess

  Player --> undoMove
  Player --> redoMove
  Player --> viewMoveHistory
  Player --> surrender
  Player --> saveGame
  Player --> moveAChess

}

usecase "Play game" as playGame
usecase "Load game" as loadGame
usecase "View match history" as viewMatchHistory
usecase "View match history detail" as viewDetailMatchHistory

Player --> playGame
Player --> loadGame
Player --> viewMatchHistory
Player --> viewDetailMatchHistory

@enduml
