|User|
start
:Select Chess Piece;

|System|
:Check Castling;
if (Castling Available?) then (yes)
  :Render Castling Move;
endif
:Render Available Cell;

|User|
:Move Chess Piece to Available Cell;
:Deselect Chess Piece;
stop

@enduml