@startuml "Activity diagram"
title "Move a chess piece"
|User|
start
:Chooses a chess piece;
|System|
:Show valid move of chess piece;

|User|
:Choose a cell want to move;

|System|
:Check valid move;
if (valid?) then (yes)
    :update chess piece to new cell;
    :Check end game|
    if (end?) then (yes)
        :Show notification "End game";
    else (no)
        :Swich player;   
    endif
else (no)
    :Show notification "You can't move \n this chess piece to this cell";

endif

stop
@enduml
