@startuml "Play a game activity diagram"
title "Game Flow"

|User|
start
repeat
:Choose a chess piece to move;

|System|
:Show valid moves;

|User|
:Choose a destination cell;

|System|
:Start timer of the player;
:Move the chess piece;
:Pause timer of the player;
:Check if game is over;

|System|
:Switch player;
repeat while (game is not over) is (true)
-> false;
|System|
:End game;
stop
@enduml
