@startuml "Activity diagram"
title "Undo Move"

start
:Player chooses save game;
:System saves games and move history to database;
if (success?) then (yes)
    :System shows notification "Save successfully";
else (no)
    :System shows notification "Save unsuccessfully";
endif

stop
@enduml
