@startuml "Activity diagram"
title "Undo Move"

start
:Player choose undo move;
if (have previous move?) then (yes)
    :System brought the piece position just moved to the previous position;
    :System switch player;
else (no)
    :System show notification "Can't undo.";
endif
stop

    @enduml
