@startuml "Activity diagram"
title "Undo Move"

start
:Player choose undo move;
if (have previous move?) then (yes)
    :System go back one step;
    :System switch player;
else (no)
    :System show notification "Can't undo.";
endif
stop
@enduml
